# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791e5d32d6593286fc86103b651684d31a57beeecbc833aa13bab5b17423b30b26becec2c5f1a3fb4e1e1b370846ebeffa73bfe1a5245ea644161365a6ba7dff

test:
  secret_key_base: c7eb8b2609c1b0d39d919793cf27407fa7fd372cce4b5a66ba77ffcbabc5a89e069d276ab45d5a352a8c9fb245310a48161757babe3492e6452f3fc3697100cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
